kafka_url = "localhost:9093"
topic = "accounts"
partition = 0
group_id = "dictionary-group"
database_url = "host=localhost port=5432 user=postgres password=postgres dbname=dictionary_dev sslmode=disable"
